vp.v.l10n['ru'] = {
'[js/]#common': '[js/]#Общий',
'[js/]User has left the conference.': '[js/]Пользователь покинул конференцию.',
'[js/]Me': '[js/]Я',
'[js/]Participants': '[js/]Participants',
'[js/]And only couple of seconds next time.': '[js/]и всего несколько секунд в следующий раз.',
'[js/]Loading VZOchat Web Client...': '[js/]Загружаю TrueConf Web Client...',
'[js/]Please wait for a while. Thank you!': '[js/]Пожалуйста, подождите немного, спасибо!',
'[js/]Usually it takes less than 30 seconds for initial download.': '[js/]Обычно установка занимает менее 30 секунд',
'[js/]Please make sure that all instances of VZOchat webclient are closed. Thank you!': '[js/]Пожалуйста, убедитесь что все прочие версии приложения VideoPort или вебклиента VideoPort закрыты, спасибо!',
'[js/]VZOchat Application is Already Open': '[js/]Вебклиент уже запущен в другом окне',
'[js/]Please upgrade to a newer version:': '[js/]Пожалуйста, установите обновление:',
'[js/]Update': '[js/]Обновление',
'[js/]Version outdated...': '[js/]Ваша версия устарела',
'[js/]Close this browser and try one more time;': '[js/]Закройте браузер и попробуйте ещё раз;',
'[js/]Download and install the latest version:': '[js/]Скачайте и установите последнюю версию:',
'[js/]If nothing helps please report this issue to your vendor.': '[js/]Обратитесь к Вашему поставщику услуг видеосвязи.',
'[js/]Plugin has crashed or didn&apos;t started?': '[js/]Произошла ошибка или веб клиент не запустился?',
'[js/]Troubleshooting': '[js/]Устранение неполадок',
'[js/]Not available': '[js/]Не доступен',
'[js/]Sorry but VZOchat Web Client only works with Windows browsers only. Try to use Wine or VMWare.': '[js/]К сожалению TrueConf Web Client может работать только с Windows браузерами. Попробуйте воспользоваться Wine или VMWare.',
'[js/]&#91;x&#93; close wizard': '[js/]&#91;x&#93; закрыть помощника',
'[js/]Click [em]Allow[/em] button.': '[js/]Нажмите на кнопку [em]Разрешить[/em].',
'[js/]Click [em]Install Now[/em].': '[js/]Затем [em]Установить сейчас[/em].',
'[js/]Install VZOchat Web Client': '[js/]Установить VideoPort Web Client',
'[js/]Restart Firefox.': '[js/]Перезапустите Firefox.',
'[js/]VZOchat Web Client for Mozilla Firefox': '[js/]Вебклиент VideoPort для Mozilla Firefox',
'[js/]VZOchat Webclient Installation': '[js/]Установка вебклиента TrueConf',
'[js/]When yellow bar above will appear just follow the steps.': '[js/]Когда сверху появится желтая полоса, следуйте инструкциям.',
'[js/][b]Important:[/b] If the installation doesn&apos;t start when you click on the link above, you have to do it manually. Save the above XPI file to your local disk by right-clicking on the link and selecting Save Link As.... Then open the saved XPI file from inside Mozilla with File -> Open File... to install it. You can also drop the saved XPI file onto the Extension Manager or the Go button.': '[js/][b]Внимание:[/b] Если установка не началась, когда вы кликнули по ссылке выше, вам придется запустить её в ручную. Для этого сохраните .xpi файл, нажав правой кнопкой мыши над ссылкой и выбрав Сохранить Как... Затем откройте сохраненный файл браузером из меню Файл -> Открыть Файл... Или перетащите скаченный файл в окно браузера.',
'[js/]Close all instances of Firefox, Chrome, Opera and Safari web browsers;': '[js/]Закройте все запущенные окна браузеров Firefox, Chrome, Opera и Safari;',
'[js/]Download an installation package with the latest version:': '[js/]Скачайте инсталлятор веб клиента по ссылке ниже:',
'[js/]Install Steps': '[js/]Шаги по установке',
'[js/]Run installer and follow the instructions.': '[js/]Запустите инсталлятор и следуйте его инструкциям.',
'[js/]If nothing happens please check that you have enabled ActiveX support in browser security settings.': '[js/]Если ничего не происходит, проверьте, что у вас включена поддержка ActiveX в настройках безопасности браузера.',
'[js/]To proceed with installation please follow the on-screen instructions on the top of this window.': '[js/]Чтобы продолжить установку, пожалуйста, следуйте инструкциям в верхней части этого экране.',
'[js/]VideoPort Web Client for Internet Explorer': '[js/]Вебклиент VideoPort для Internet Explorer',
'[js/]Guest %id': '[js/]Гость %id',
'[js/]Mute on/off sound notifications': '[js/]Отключить/включить звуковые оповещения',
'[js/]Message was sent to offline user...': '[js/]сообщение отправлено отключенному пользователю...',
'[js/]Loading TrueConf Web Client...': '[js/]Загружаю TrueConf Web Client...',
'[js/]NOTE: You have to close all instances of Firefox, Chrome, Opera and Safari web browsers before proceeding with install.': '[js/]ВНИМАНИЕ: Перед установкой необходимо закрыть все запущенные окна браузеров Firefox, Chrome, Opera и Safari.',
'[js/]Please download an installation package with the latest version:': '[js/]Скачайте последний инсталлятор веб клиента по ссылке ниже:',
'[js/]Your version is outdated': '[js/]Ваша версия устарела',
'[js/]close this message': '[js/]закрыть это сообщение',
'[js/]Internet User': '[js/]Интернет пользователь',
'empty':''};