<?
$PERM["tools"]["29"]="T_8";
$PERM["rk.php"]["29"]="T_8";
$PERM["admin"]["12"]="T_8";
$PERM["admin"]["9"]="T_8";
$PERM["admin"]["8"]="T_8";
$PERM["admin"]["6"]="T_8";
$PERM["admin"]["5"]="T_8";
$PERM["admin"]["*"]="D";
?>