CREATE TABLE IF NOT EXISTS b_rest_event
(
	ID int(11) NOT NULL AUTO_INCREMENT,
	APP_ID int(11) NULL,
	EVENT_NAME varchar(255) NOT NULL ,
	EVENT_HANDLER varchar(255) NOT NULL,
	USER_ID int(11) NULL DEFAULT 0,
	TITLE VARCHAR(255) NULL DEFAULT '',
	COMMENT VARCHAR(255) NULL DEFAULT '',
	DATE_CREATE DATETIME NULL,
	APPLICATION_TOKEN VARCHAR(50) NULL DEFAULT '',
	PRIMARY KEY (ID),
	UNIQUE ux_b_rest_event_app_event (APP_ID, EVENT_NAME(100), EVENT_HANDLER(200), USER_ID),
	INDEX ix_b_rest_event_app_id (APP_ID),
	INDEX ix_b_rest_event_event_name (EVENT_NAME)
);

CREATE TABLE IF NOT EXISTS b_rest_app
(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	CLIENT_ID VARCHAR(128) NOT NULL,
	CODE VARCHAR(128) NOT NULL,
	ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
	INSTALLED CHAR(1) NOT NULL DEFAULT 'N',
	URL VARCHAR(1000) NOT NULL,
	URL_DEMO VARCHAR(1000) NULL,
	URL_INSTALL VARCHAR(1000) NULL,
	VERSION VARCHAR(4) NULL DEFAULT '1',
	SCOPE VARCHAR(2000) NOT NULL,
	STATUS CHAR(1) NOT NULL DEFAULT 'F',
	DATE_FINISH DATE NULL,
	IS_TRIALED CHAR(1) NULL DEFAULT 'N',
	SHARED_KEY VARCHAR(32) NULL DEFAULT NULL,
	CLIENT_SECRET VARCHAR(100) NULL DEFAULT NULL,
	APP_NAME VARCHAR(1000) NULL DEFAULT NULL,
	ACCESS VARCHAR(2000) NULL DEFAULT '',
	APPLICATION_TOKEN VARCHAR(50) NULL DEFAULT '',
	MOBILE CHAR(1) NULL DEFAULT 'N',
	PRIMARY KEY (ID),
	UNIQUE INDEX ux_b_rest_app1 (CLIENT_ID)
);

CREATE TABLE IF NOT EXISTS b_rest_app_lang
(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	APP_ID INT(11) NOT NULL,
	LANGUAGE_ID CHAR(2) NOT NULL,
	MENU_NAME VARCHAR(500) NULL,
	PRIMARY KEY (ID),
	UNIQUE INDEX ux_b_rest_app_lang1 (APP_ID, LANGUAGE_ID)
);

CREATE TABLE IF NOT EXISTS b_rest_ap
(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	USER_ID INT(11) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	ACTIVE CHAR(1) NULL DEFAULT 'Y',
	TITLE VARCHAR(255) NULL DEFAULT '',
	COMMENT VARCHAR(255) NULL DEFAULT '',
	DATE_CREATE DATETIME NULL,
	DATE_LOGIN DATETIME NULL,
	LAST_IP VARCHAR(255) NULL,
	PRIMARY KEY (ID),
	INDEX ix_b_rest_ap (USER_ID, PASSWORD, ACTIVE)
);

CREATE TABLE IF NOT EXISTS b_rest_ap_permission
(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	PASSWORD_ID INT(11) NOT NULL,
	PERM VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE INDEX ux_b_rest_ap_perm1 (PASSWORD_ID,PERM)
);

CREATE TABLE IF NOT EXISTS b_rest_log
(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	TIMESTAMP_X TIMESTAMP NOT NULL DEFAULT current_timestamp,
	CLIENT_ID VARCHAR(45) NULL,
	PASSWORD_ID INT(11) NULL,
	SCOPE VARCHAR(50) NULL,
	METHOD VARCHAR(255) NULL,
	REQUEST_METHOD VARCHAR(10) NULL,
	REQUEST_URI VARCHAR(255) NULL,
	REQUEST_AUTH TEXT NULL,
	REQUEST_DATA TEXT NULL,
	RESPONSE_STATUS VARCHAR(20) NULL,
	RESPONSE_DATA TEXT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_rest_placement
(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	APP_ID INT(11) NULL,
	PLACEMENT VARCHAR(255) NOT NULL,
	PLACEMENT_HANDLER VARCHAR(255) NOT NULL,
	TITLE VARCHAR(255) NULL DEFAULT '',
	COMMENT VARCHAR(255) NULL DEFAULT '',
	DATE_CREATE DATETIME NULL,
	PRIMARY KEY (ID),
	UNIQUE ux_b_rest_placement1 (APP_ID, PLACEMENT(100), PLACEMENT_HANDLER(200)),
	INDEX ix_b_rest_placement3 (PLACEMENT)
);

